Sprint 16. Django Forms/om-54-team-21/library/author/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create_author/', views.AuthorFormView.as_view(), name='create_author'),
    path('create_author/success/', views.success_author_creation, name='success'),
    path('show_authors/', views.show_authors, name='show_authors'),
    path('remove_author/', views.remove_author, name='remove_author'),
    path('update/<int:author_id>', views.update_author, name='update_author'),
]

Sprint 16. Django Forms/om-54-team-21/library/book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('', views.list_books, name='books'),
    path('<int:book_id>', views.detail, name='book_detail'),
    path('user_book/<int:user_id>', views.show_book_for_specific_user, name='user_detail_book'),
    path('create_book/', views.create_book, name='create_book'),
    path('delete_book/<int:pk>/', views.delete_book, name='delete_book'),
    path('success_book_creation/<str:name>', views.success_book_creation, name='success_book'),
    path('success_book_deletion/', views.success_book_deletion, name='success_delete_book'),
    path('update/<int:book_id>', views.update_book, name='update_book'),

]

Sprint 16. Django Forms/om-54-team-21/library/library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include('book.urls')),
    path('authentication/', include(('authentication.urls', 'authentication'),
                                    namespace='authentication')),
    path('author/', include(('author.urls', 'author'), namespace='author')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    path('', include(('authentication.urls', 'main_page'),
                     namespace='main_page')),
]

Sprint 16. Django Forms/om-54-team-21/library/author/models.py
from django.db import models

import book.models


class Author(models.Model):
    """
        This class represents an Author. \n
        Attributes:
        -----------
        param name: Describes name of the author
        type name: str max_length=20
        param surname: Describes last name of the author
        type surname: str max_length=20
        param patronymic: Describes middle name of the author
        type patronymic: str max_length=20
    """
    name = models.CharField(blank=True, max_length=20)
    surname = models.CharField(blank=True, max_length=20)
    patronymic = models.CharField(blank=True, max_length=20)
    books = models.ManyToManyField(book.models.Book, related_name='authors')
    id = models.AutoField(primary_key=True)

    def __str__(self):
        """
        Magic method is redefined to show all information about Author.
        :return: author id, author name, author surname, author patronymic
        """
        # return f"\'id\': {self.pk}, \'name\': \'{self.name}\'," \
        #        f" \'surname\': \'{self.surname}\', \'patronymic\': \'{self.patronymic}\'"
        return f"id: {self.pk} name: {self.name}"

    def __repr__(self):
        """
        This magic method is redefined to show class and id of Author object.
        :return: class, id
        """
        return f"Author(id={self.pk})"

    @staticmethod
    def get_by_id(author_id):
        """
        :param author_id: SERIAL: the id of a Author to be found in the DB
        :return: author object or None if a user with such ID does not exist
        """
        # return Author.objects.filter(id=author_id)
        # return Author.get_by_id(author_id)
        # return  Author.get_object_or_404()
        try:
            return Author.objects.get(pk=author_id)
        except:
            return None

    @staticmethod
    def delete_by_id(author_id):
        """
        :param author_id: an id of a author to be deleted
        :type author_id: int
        :return: True if object existed in the db and was removed or False if it didn't exist
        """
        try:
            author = Author.objects.get(pk=author_id)
            author.delete()
            return True
        except:
            return False

    @staticmethod
    def create(name, surname, patronymic):
        """
        param name: Describes name of the author
        type name: str max_length=20
        param surname: Describes surname of the author
        type surname: str max_length=20
        param patronymic: Describes patronymic of the author
        type patronymic: str max_length=20
        :return: a new author object which is also written into the DB
        """
        if name and len(name) <= 20 and surname and len(surname) <= 20 and patronymic and len(patronymic) <= 20:
            author = Author(name=name, surname=surname, patronymic=patronymic)
            author.save()
            return author

    def to_dict(self):
        """
        :return: author id, author name, author surname, author patronymic
        :Example:
        | {
        |   'id': 8,
        |   'name': 'fn',
        |   'surname': 'mn',
        |   'patronymic': 'ln',
        | }
        """
        # return self.__dict__

    def update(self,
               name=None,
               surname=None,
               patronymic=None):
        """
        Updates author in the database with the specified parameters.\n
        param name: Describes name of the author
        type name: str max_length=20
        param surname: Describes surname of the author
        type surname: str max_length=20
        param patronymic: Describes patronymic of the author
        type patronymic: str max_length=20
        :return: None
        """

        if name and len(name) <= 20:
            self.name = name
        if surname and len(surname) <= 20:
            self.surname = surname
        if patronymic and len(patronymic) <= 20:
            self.patronymic = patronymic
        self.save()

    @staticmethod
    def get_all():
        """
        returns data for json request with QuerySet of all authors
        """
        return Author.objects.all()

Sprint 16. Django Forms/om-54-team-21/library/author/forms.py
from django import forms
from .models import Author


class AuthorFormModel(forms.ModelForm):
    """Send the data to model Author"""
    class Meta:
        model = Author
        fields = ['name', 'patronymic', 'surname']


class UpdateAuthorFormModel(forms.ModelForm):
    """Send the data to model Author"""
    class Meta:
        model = Author
        exclude = ['books']

Sprint 16. Django Forms/om-54-team-21/library/author/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import FormView
from .forms import *
from . import models


def create_author(request):
    if request.method == 'POST':
        data = request.POST
        author = models.Author.create(data['name'],
                                      data['surname'],
                                      data['patronymic'])
        return render(request, 'author/create_author.html', {'author': author})
    return render(request, 'author/create_author.html')


# show information about all authors (librarian)
def show_authors(request):
    authors = models.Author.get_all()
    return render(request, 'author/show_authors.html', {'authors': authors})


# provide the ability to remove the author if he is not attached to
# any book (librarian)
def remove_author(request):
    authors = models.Author.get_all()
    if request.method == 'POST':
        author_id = request.POST['authors']
        if author_id != 'False':
            author = models.Author.objects.get(id=author_id)
            if not len(author.books.all()):
                models.Author.delete_by_id(author_id)
                authors = models.Author.get_all()
            return render(request, 'author/remove_author.html',
                      {'authors': authors,
                       'deleted_author': author})

    return render(request, 'author/remove_author.html', {'authors': authors})


class AuthorFormView(FormView):
    """Serves for transition of information from front-end into form of model Author"""
    form_class = AuthorFormModel
    template_name = 'author/create_author.html'
    success_url = '/author/create_author/success/'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


def success_author_creation(request):
    """Notification in case of successful creation of a new author."""
    return HttpResponse("<script>alert ('Congratulations! The author was successfully created!'); "
                        "window.location = '/author/show_authors/';</script>")


def update_author(request, author_id=None):
    if author_id:
        try:
            author = Author.objects.get(pk=author_id)
        except:
            return redirect('/author/show_authors/')
        else:
            form = UpdateAuthorFormModel(initial=
                                        {'name': author.name,
                                         'surname': author.surname,
                                         'patronymic': author.patronymic,
                                         'books': author.books,
                                         })

            if request.method == 'POST':
                form = UpdateAuthorFormModel(request.POST)

                if form.is_valid():
                    data = form.cleaned_data
                    author.name = data.get('name')
                    author.surname = data.get('surname')
                    author.patronymic = data.get('patronymic')
                    author.save()
                    print("cleaned data:", form.cleaned_data)
                    return redirect('/author/show_authors/')

            else:
                return render(request, 'author/update_author.html', {'form': form})
    else:
        return redirect('/author/show_authors/')

Sprint 16. Django Forms/om-54-team-21/library/author/templates/author/create_author.html
{% extends 'base.html' %}
{% block styles %}
{% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'author/css/style.css' %}">
{% endblock %}
{% block title %}
Create author
{% endblock %}


{% block content %}
  {% if request.user.role %}
    {% if author %}
      <div class="successAdded"> Successful added author {{ author.name }} </div>
    {% endif %}
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="create_author">
        <label for="{{ form.name.id_for_label }}">Author name</label><br>
        {{ form.name }}
        </div>
        <div class="create_author">
        <label for="{{ form.patronymic.id_for_label }}">Patronymic</label><br>
        {{ form.patronymic }}
        </div>
        <div class="create_author">
        <label for="{{ form.surname.id_for_label }}">Author surname</label><br>
        {{ form.surname }}
        </div>
        <input type="submit" value="Add Author" style="text-decoration: #080710; font-weight: bold;">
    </form>
{#      <form action="" method="post">#}
{#      {% csrf_token %}#}
{#      <label for="name">Author name:</label><br>#}
{#      <input type="text" name="name" id="name" value="name" onfocus="this.value=''"><br>#}
{##}
{#      <label for="surname">Author surname:</label><br>#}
{#      <input type="text" name="surname" id="surname" value="surname" onfocus="this.value=''"><br>#}
{##}
{#      <label for="patronymic">Patronymic:</label><br>#}
{#      <input type="text" name="patronymic" id="patronymic" value="patronymic" onfocus="this.value=''"><br>#}
{##}
{#      <input type="submit" value="Add author">#}
{#    </form>#}
  {% else %}
    <h2 class="warning">Access Denied <hr> <span class="black">Only librarian manage create
      authors</span></h2>
  {% endif %}
{% endblock %}

Sprint 16. Django Forms/om-54-team-21/library/author/templates/author/remove_author.html
{% extends 'base.html' %}
{% block styles %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'author/css/style.css' %}">
{% endblock %}
{% block title %}
  Remove author
{% endblock %}


{% block content %}
  {% if request.user.role %}
    {% if deleted_author %}
      <div class="successAdded"> Successful deleted author {{ deleted_author.name }} </div>
    {% endif %}
    <form class="deleteAuthorForm" action="" method="post">
      {% csrf_token %}
      <label for="authors">Choose an author you want to delete:</label>

      <select name="authors" id="authors-select">
        <option value="False">--Please choose an option--</option>
        {% for author in authors %}
          <option value="{{ author.id }}">{{ author }}</option>
        {% endfor %}

      </select>
      <input type="submit" value="Delete">
    </form>
  {% else %}
    <h2 class="warning">Access Denied <hr> <span class="black">Only librarian manage create
      authors</span></h2>
  {% endif %}
{% endblock %}

Sprint 16. Django Forms/om-54-team-21/library/author/templates/author/show_authors.html
{% extends 'base.html' %}
{% block styles %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'author/css/style.css' %}">
{% endblock %}
{% block title %}
  Show all authors
{% endblock %}
{% block content %}
  <table>
    <caption><h2> Authors </h2></caption>
    <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Patronymic</th>
    </tr>
    </thead>
    <tbody>


    {% for author in authors %}
      <tr>
        <td>{{ author.name }}</td>
        <td>{{ author.surname }}</td>
        <td>{{ author.patronymic }}</td>
      <td><a href="{% url 'author:update_author' author_id=author.id %}">Edit author</a></td>
      </tr>

    {% endfor %}
    </tbody>
  </table>
  <hr>
  {% if request.user.role %}
  <div class="flexLinks">
    <div><a href="{% url 'author:create_author' %}">Create author</a></div>
    <div><a href="{% url 'author:remove_author' %}">Remove author</a></div>
  </div>
  {% endif %}
{% endblock %}

Sprint 16. Django Forms/om-54-team-21/library/author/templates/author/update_author.html
{% extends 'base.html' %}
{% block styles %}
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'author/css/style.css' %}">
{% endblock %}
{% block title %}Update author{% endblock %}
{% block content %}
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
        <div class="create_author">
        <label>{{ field.label_tag }}</label><br>
        {{ field }}
        </div>
        {% endfor %}
        <input type="submit" value="Update Author" style="text-decoration: #080710; font-weight: bold;">

  </form>
{% endblock %}