Sprint 16. Django Forms/om-54-team-21/library/book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('', views.list_books, name='books'),
    path('<int:book_id>', views.detail, name='book_detail'),
    path('user_book/<int:user_id>', views.show_book_for_specific_user, name='user_detail_book'),
    path('create_book/', views.create_book, name='create_book'),
    path('delete_book/<int:pk>/', views.delete_book, name='delete_book'),
    path('success_book_creation/<str:name>', views.success_book_creation, name='success_book'),
    path('success_book_deletion/', views.success_book_deletion, name='success_delete_book'),
    path('update/<int:book_id>', views.update_book, name='update_book'),

]

Sprint 16. Django Forms/om-54-team-21/library/library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include('book.urls')),
    path('authentication/', include(('authentication.urls', 'authentication'),
                                    namespace='authentication')),
    path('author/', include(('author.urls', 'author'), namespace='author')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    path('', include(('authentication.urls', 'main_page'),
                     namespace='main_page')),
]

Sprint 16. Django Forms/om-54-team-21/library/order/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('all/', views.show_all_orders, name='orders'),
    path('own/', views.show_own_orders, name='order'),
    path('create/', views.create_an_order, name='new_order'),
    path('del/', views.del_order_by_root, name='del_order'),
    path('del/<int:order_id>', views.del_order_by_root, name='del_order'),
    path('update/<int:order_id>', views.upd_order, name='upd_order'),
]

Sprint 16. Django Forms/om-54-team-21/library/order/models.py
from django.db import models, DataError

from authentication.models import CustomUser
from book.models import Book


class Order(models.Model):
    """
           This class represents an Order. \n
           Attributes:
           -----------
           param book: foreign key Book
           type book: ForeignKey
           param user: foreign key CustomUser
           type user: ForeignKey
           param created_at: Describes the date when the order was created. Can't be changed.
           type created_at: int (timestamp)
           param end_at: Describes the actual return date of the book. (`None` if not returned)
           type end_at: int (timestamp)
           param plated_end_at: Describes the planned return period of the book (2 weeks from the moment of creation).
           type plated_end_at: int (timestamp)
       """
    book = models.ForeignKey(Book, on_delete=models.CASCADE, default=None)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    end_at = models.DateTimeField(default=None, null=True, blank=True)
    plated_end_at = models.DateTimeField(default=None)

    def __str__(self):
        """
        Magic method is redefined to show all information about Book.
        :return: book id, book name, book description, book count, book authors
        """
        # if self.end_at == None:
        #     return f"\'id\': {self.pk}, " \
        #            f"\'user\': CustomUser(id={self.user.pk})," \
        #            f" \'book\': Book(id={self.book.pk})," \
        #            f" \'created_at\': \'{self.created_at}\'," \
        #            f" \'end_at\': {self.end_at}," \
        #            f" \'plated_end_at\': \'{self.plated_end_at}\'"
        # else:
        #     return f"\'id\': {self.pk}, " \
        #            f"\'user\': CustomUser(id={self.user.pk})," \
        #            f" \'book\': Book(id={self.book.pk})," \
        #            f" \'created_at\': \'{self.created_at}\'," \
        #            f" \'end_at\': \'{self.end_at}\'," \
        #            f" \'plated_end_at\': \'{self.plated_end_at}\'"
        return f"id: {self.pk} user: {self.user.pk}" \
               f" book:{self.book.pk}"
    def __repr__(self):
        """
        This magic method is redefined to show class and id of Book object.
        :return: class, id
        """
        return f'{self.__class__.__name__}(id={self.id})'

    def to_dict(self):
        """
                :return: order id, book id, user id, order created_at, order end_at, order plated_end_at
                :Example:
                | {
                |   'id': 8,
                |   'book': 8,
                |   'user': 8',
                |   'created_at': 1509393504,
                |   'end_at': 1509393504,
                |   'plated_end_at': 1509402866,
                | }
                """
        pass

    @staticmethod
    def create(user, book, plated_end_at):
        orders = Order.objects.all()
        books = set()
        for order in orders:
            if not order.end_at:
                books.add(order.book.id)
        if book.id in books and book.count == 1:
            return None
        try:
            # Python – django.db.utils.IntegrityError: FOREIGN KEY constraint failed
            order = Order(user=user, book=book, plated_end_at=plated_end_at)
            order.save()
            return order
        except ValueError:
            return None
        except DataError:
            return None

    @staticmethod
    def get_by_id(order_id):
        try:
            return Order.objects.get(pk=order_id)
        except:
            return None

    def update(self, plated_end_at=None, end_at=None):
        if plated_end_at != None:
            self.plated_end_at = plated_end_at
        if end_at != None:
            self.end_at = end_at
        self.save()

    @staticmethod
    def get_all():
        return list(Order.objects.all())

    @staticmethod
    def get_not_returned_books():
        return Order.objects.filter(end_at=None).values()

    @staticmethod
    def delete_by_id(order_id):
        try:
            a = Order.objects.get(pk=order_id)
        except:
            return False
        else:
            a.delete()
            return True

    @staticmethod
    def get_all_by_user_id(user_id):
        return Order.objects.filter(user__id=user_id)

Sprint 16. Django Forms/om-54-team-21/library/order/forms.py
from django import forms
from .models import Order


class DateInput(forms.DateInput):
    input_type = 'date'



class OrderModelFormForAdmin(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['user', 'book', 'end_at']
        labels = {
            'user': 'Select user',
            'book': 'Select book',
            'end_at': 'Date to end subscribe',
        }
        widgets = {
            'end_at' : DateInput
        }
class OrderModelFormForUser(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['book', 'end_at']
        labels = {
            # 'user': 'Select user',
            'book': 'Select book',
            'end_at': 'Date to end subscribe',
        }
        widgets = {
            'end_at' : DateInput
        }


class DeleteOrderUser(forms.Form):
    orders = forms.IntegerField(required=True,
                                label="Choose order id:")


class DeleteOrderAdmin(forms.Form):

    orders = forms.ModelChoiceField(Order.objects.all(),
                                       required=True,
                                       label="Choose order:")


class UpdateOrderModelForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['book', 'plated_end_at']
        labels = {
            'book': 'Select book',
            'plated_end_at': 'Date to end subscribe',
        }
        widgets = {
            'plated_end_at' : DateInput
        }

Sprint 16. Django Forms/om-54-team-21/library/order/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .models import Order
from authentication.models import CustomUser
from book.models import Book
# from datetime import datetime
import datetime

from .forms import OrderModelFormForAdmin, OrderModelFormForUser, \
    DeleteOrderUser, DeleteOrderAdmin, UpdateOrderModelForm

def show_all_orders(request):
    if request.user.is_authenticated and request.user.role == 1:
        data = Order.get_all()
        context = {'list_of_order': data}
        return render(request, 'order/order_all.html', context)

    return render(request, 'order/order_all.html', {})


def show_own_orders(request):
    if request.user.is_authenticated:
        user_id = request.user.id
        if user_id:
            try:
                data = list(Order.get_all_by_user_id(user_id))
                context = {'order_by_id': data}
                return render(request, 'order/order_own_list.html', context)
            except:
                return render(request, 'order/order_own_list.html',
                              {'order_by_id': "None order"})

    return render(request, 'order/order_own_list.html', {})


def create_an_order(request):
    form = OrderModelFormForUser()
    if request.user.is_authenticated:
        if request.user.role:
            form = OrderModelFormForAdmin()
            if request.method == 'POST':
                form = OrderModelFormForAdmin(request.POST)
                if form.is_valid():
                    cd = form.cleaned_data
                    order = Order.create(cd['user'], cd['book'], cd['end_at'])
                    return render(request, 'order/order_create.html',
                                  {'resolt': f"Order # {str(order.id)} created",
                                   'form': form})
            else:
                return render(request, 'order/order_create.html',
                              {'form': form})

        else:
            if request.method == 'POST':
                form = OrderModelFormForUser(request.POST)

                if form.is_valid():
                    cd = form.cleaned_data
                    order = Order.create(request.user, cd['book'], cd['end_at'])
                    return render(request, 'order/order_create.html',
                                  {'resolt': f"Order # {order.id} created",
                                   'form': form
                                   })
                return render(request, 'order/order_create.html',{
                    'resoltError': "Error", 'form': form})

    return render(request, 'order/order_create.html', {'form': form})


def del_order_by_root(request, order_id=None):
    if request.user.role:
        if order_id:
            order = Order.objects.get(id=order_id)
            order.delete()
            return redirect(reverse_lazy('order:orders'))

        orders = Order.objects.all()
        form = DeleteOrderAdmin()
        if request.method == 'POST':
            form = DeleteOrderAdmin(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                Order.delete_by_id(cd['orders'].id)
                return render(request, 'order/del_order.html',
                              {'form': form,})

        else:
            return render(request, 'order/del_order.html', {'form': form,
                                                            'orders': orders})


    else:
        if order_id:
            order = Order.objects.filter(id=order_id)
            if order[0].user.id == request.user.id:
                # pass
                order.delete()


        return redirect(reverse_lazy('order:order'))

    return render(request, 'order/del_order.html', {'form': form,
                                                    'orders': orders})


def upd_order(request, order_id=None):
    if order_id:

        order = Order.objects.get(id=order_id)
        form = UpdateOrderModelForm(initial=
                                    {'book': order.book,
                                     'plated_end_at': order.plated_end_at.date()
                                     },
                                    instance=Order
                                    )

        if request.method == 'POST':
            form = UpdateOrderModelForm(request.POST, instance=Order())

            if order.user.id == request.user.id or request.user.role:

                if form.is_valid():
                    ord = form.save(commit=False)
                    ord.user = order.user
                    ord.id = order.id
                    ord.created_at = order.created_at
                    ord.save()

            if request.user.role:
                return redirect(reverse_lazy('order:orders'))
            return redirect(reverse_lazy('order:order'))

        else:
            return render(request, 'order/upd_order.html', {'form': form})

    if request.user.role:
        return redirect(reverse_lazy('order:orders'))
    return redirect(reverse_lazy('order:order'))

Sprint 16. Django Forms/om-54-team-21/library/order/templates/order/del_order.html
{% extends 'base.html' %}
{% block styles %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'author/css/style.css' %}">
{% endblock %}
{% block title %}Order root operations{% endblock %}
{% block content %}
{% if message %}

{% endif %}
<form action="" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Del order">
</form><br><br>


  {% if orders %}
    <table>
      <caption><h2> Orders </h2></caption>
      <thead>
      <tr>
        <th>ID</th>
        <th>Book</th>
        <th>Book id</th>
        <th>Date</th>
        <th>User id</th>
        <th>User email</th>
      </tr>
      </thead>
      <tbody>
      {% for order in orders %}
       <tr>
          <td>{{ order.id }}</td>
          <td>{{ order.book.name }}</td>
          <td>{{ order.book.id }}</td>
          <td>{{ order.created_at }}</td>
          <td>{{ order.user.id }}</td>
          <td>{{ order.user.email }}</td>
       </tr>
      {% endfor %}
       </tbody>
    </table>
  {% endif %}
  <hr>
{% endblock %}

Sprint 16. Django Forms/om-54-team-21/library/order/templates/order/order_all.html
{% extends 'base.html' %}
{% block styles %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'author/css/style.css' %}">
{% endblock %}
{% block title %}List of users{% endblock %}
{% block content %}
  {% if list_of_order %}

    <table>
      <caption><h2> Orders </h2></caption>
      <thead>
      <tr>
        <th>ID</th>
        <th>Book</th>
        <th>Date</th>
        <th>User id</th>
        <th>User email</th>
        <th>Del </th>
        <th>Modification </th>
      </tr>
      </thead>
      <tbody>
      {% for order in list_of_order %}
       <tr>
          <td>{{ order.id }}</td>
          <td>{{ order.book.name }}</td>
          <td>{{ order.created_at }}</td>
         <td>{{ order.user.id }}</td>
         <td>{{ order.user.email }}</td>
          <td><a class="delItem" data-order-id="{{ order.id }}"href="{% url 'order:del_order' order.id %}">X</a> </td>
          <td><a href="{% url 'order:upd_order' order.id %}">Upd</a> </td>
        </tr>
      {% endfor %}
       </tbody>
    </table>
    <hr>
  {% else %}
    <caption><h2 style="text-align: center"> Create new order </h2></caption>

  {% endif %}

  <div class="flexLinks">
    <div><a href="{% url 'order:new_order' %}">Create order</a></div>
    {% if order_by_id and request.user.is_authenticated %}

    <div><a href="{% url 'order:del_order' %}">Remove order</a></div>
    {% endif %}
  </div>

  <script>
      const delUserLink = document.querySelectorAll('.delItem')
      delUserLink.forEach(e => e.addEventListener('click', function (elem){
              let dataPrompt = prompt('Are you sure to delete. Write id order for confirm' + ' ' +  this.dataset.orderId)
              if (dataPrompt !== this.dataset.orderId){
                  elem.preventDefault()
              }
          })
      )
  </script>
{% endblock %}

Sprint 16. Django Forms/om-54-team-21/library/order/templates/order/order_create.html
{% extends 'base.html' %}
{% block styles %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'author/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'order/css/style.css' %}">
{% endblock %}
{% block title %}Create new order{% endblock %}
{% block content %}

  {% if resolt %}
    <div class="successAdded"> Successful added order {{ resolt }} </div>
  {% endif %}
  <form class="orderAddForm" action="" method="post">

      {% csrf_token %}

      {{ form.as_table }}<br><br>

      <input type="submit" value="Submit">

  </form>

{#<a>{{resolt}}</a>#}
{% endblock %}

Sprint 16. Django Forms/om-54-team-21/library/order/templates/order/order_own_list.html
{% extends 'base.html' %}
{% block styles %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'author/css/style.css' %}">
{% endblock %}
{% block title %}List of users{% endblock %}
{% block content %}

  {% if order_by_id %}

  <table>
    <caption><h2> Your Orders </h2></caption>
    <thead>
    <tr>
      <th>Book name</th>
      <th>User email</th>
      <th>Until </th>
      <th>Del </th>
      <th>Modification </th>
    </tr>
    </thead>
    <tbody>


    {% for order in order_by_id %}
      <tr>
        <td>{{ order.book.name }}</td>
        <td>{{ order.user.email }}</td>
        <td>{{ order.plated_end_at }}</td>
        <td><a href="{% url 'order:del_order' order.id %}">X</a> </td>
        <td><a href="{% url 'order:upd_order' order.id %}">Upd</a> </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  <hr>
{#  {% if request.user.role %}#}

  {% else %}
    <caption><h2 style="text-align: center"> Create new order </h2></caption>

  {% endif %}
  <div class="flexLinks">
    <div><a href="{% url 'order:new_order' %}">New order</a></div>

  </div>
  {#  {% endif %}#}

{% endblock %}

Sprint 16. Django Forms/om-54-team-21/library/order/templates/order/upd_order.html
{% extends 'base.html' %}
{% block styles %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'author/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'order/css/style.css' %}">
{% endblock %}
{% block title %}Create new order{% endblock %}
{% block content %}

  {% if resolt %}
    <div class="successAdded"> Successful update order {{ resolt }} </div>
  {% endif %}
  <form class="orderAddForm" action="" method="post">

    {% csrf_token %}

    {{ form.as_table }}<br><br>

    <input type="submit" value="Submit">

  </form>

  {#<a>{{resolt}}</a>#}
{% endblock %}