12_sprint_MVC_MTV/om-54-team_11/library/author/urls.py
from django.urls import path, include
from . import views

app_name = 'author'
urlpatterns = [
    path('', views.author, name='author_page')
]

12_sprint_MVC_MTV/om-54-team_11/library/book/urls.py
from django.urls import path
from . import views


app_name = 'book'
urlpatterns = [
    path('', views.book, name='book_page')
]

12_sprint_MVC_MTV/om-54-team_11/library/library/urls.py
from django.urls import include, path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.main),
    path('author/', include('author.urls')),
    path('book/', include('book.urls')),
    path('order/', include('order.urls')),
    path('user/', include('user.urls')),
]

12_sprint_MVC_MTV/om-54-team_11/library/order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('', views.order, name='order_page')
]

12_sprint_MVC_MTV/om-54-team_11/library/user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('', views.user, name='user_page')
]

12_sprint_MVC_MTV/om-54-team_11/library/author/models.py
from django.db import models

# Create your models here.

12_sprint_MVC_MTV/om-54-team_11/library/book/models.py
from django.db import models

# Create your models here.

12_sprint_MVC_MTV/om-54-team_11/library/order/models.py
from django.db import models

# Create your models here.

12_sprint_MVC_MTV/om-54-team_11/library/user/models.py
from django.db import models

# Create your models here.

12_sprint_MVC_MTV/om-54-team_11/library/author/views.py
from django.shortcuts import render

# Create your views here.


def author(requests):
    return render(requests, 'author/authorPage.html', {})

12_sprint_MVC_MTV/om-54-team_11/library/book/views.py
from django.shortcuts import render

# Create your views here.


def book(requests):
    return render(requests, 'book/bookPage.html', {})

12_sprint_MVC_MTV/om-54-team_11/library/library/views.py
from django.shortcuts import render


def main(requests):
    return render(requests, 'main.html', {})

12_sprint_MVC_MTV/om-54-team_11/library/order/views.py
from django.shortcuts import render

# Create your views here.


def order(requests):
    return render(requests, 'order/orderPage.html', {})

12_sprint_MVC_MTV/om-54-team_11/library/user/views.py
from django.shortcuts import render

# Create your views here.


def user(requests):
    return render(requests, 'user/userPage.html', {})

12_sprint_MVC_MTV/om-54-team_11/library/order/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}{% endblock %}
  </title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
<div class="header">
  <div class="text-header">
    <h1><a href="/">Welcome to my Page</a><br></h1>
  </div>

  <nav>
    <ul class="menu-list">
      <li class="menu-list-item">
        <a href="{% url 'author:author_page' %}">Author</a>
      </li>
      <li class="menu-list-item">
        <a href="{% url 'book:book_page' %}">Book</a>
      </li>
      <li class="menu-list-item">
        <a href="{% url 'order:order_page' %}">Orders</a>
      </li>
      <li class="menu-list-item">
        <a href="{% url 'user:user_page' %}">Users</a>
      </li>
    </ul>
  </nav>
</div>

<hr>
{% block content %}
{% endblock %}
</body>
</html>