Sprint 16. Django Forms/om-54-team-21/library/authentication/urls.py
from django.urls import path
from django.contrib.auth import views
from . import views


urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('change-password/<int:user_id>/', views.change_password,
         name='change_password'),
    path('users/all/', views.show_all_users, name='users'),
    path('users/', views.role_of_user, name='specific_user'),
    path('users/update_user/<int:user_id>/',
         views.update_user, name='update_user'),
    path('users/del_user/<int:user_id>/',
         views.del_user, name='del_user'),
    path('', views.main, name='main'),

]

Sprint 16. Django Forms/om-54-team-21/library/book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('', views.list_books, name='books'),
    path('<int:book_id>', views.detail, name='book_detail'),
    path('user_book/<int:user_id>', views.show_book_for_specific_user, name='user_detail_book'),
    path('create_book/', views.create_book, name='create_book'),
    path('delete_book/<int:pk>/', views.delete_book, name='delete_book'),
    path('success_book_creation/<str:name>', views.success_book_creation, name='success_book'),
    path('success_book_deletion/', views.success_book_deletion, name='success_delete_book'),
    path('update/<int:book_id>', views.update_book, name='update_book'),

]

Sprint 16. Django Forms/om-54-team-21/library/library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include('book.urls')),
    path('authentication/', include(('authentication.urls', 'authentication'),
                                    namespace='authentication')),
    path('author/', include(('author.urls', 'author'), namespace='author')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    path('', include(('authentication.urls', 'main_page'),
                     namespace='main_page')),
]

Sprint 16. Django Forms/om-54-team-21/library/authentication/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UsernameField, PasswordChangeForm
from django.forms import ModelForm, Textarea
from .models import CustomUser
from django.core.validators import validate_email

import re

EMAIL_REGEX = r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)"


class CustomUserModelFormRegister(forms.ModelForm):
    error_messages = {
        "password_mismatch": "The two password fields didn’t match.",
        'incorrect_data': "Incorrect data",
    }
    email = forms.CharField(required=True,
                            max_length=80,
                            validators=[validate_email])

    password1 = forms.CharField(
        label="Password",
        strip=False,
        required=True,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        # help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
        required=True,
        # help_text="Enter the same password as before, for verification.",
    )
    class Meta:
        model = CustomUser
        fields = ['email', 'first_name', 'middle_name', 'last_name', 'role']
        # field_classes = {"email": UsernameField}


        labels = {
            'email': 'Email!',
        }
        help_texts = {
            # 'email': 'Some useful help text.',
        }
        error_messages = {
            'email': {
                'correct_mail': "This email must be like user@mail.com.",
            },
        }


class LoginForm(forms.Form):
    """
    Base class for authenticating users. Extend this to get a form that accepts
    username/password logins.
    """

    username = UsernameField(widget=forms.TextInput(attrs={"autofocus": True}))
    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password"}),
    )

    error_messages = {
        "invalid_login": (
            "Please enter a correct %(username)s and password. Note that both "
            "fields may be case-sensitive."
        ),
        "inactive": ("This account is inactive."),
    }


class UpdateUserModelForm(forms.ModelForm):
    id = forms.IntegerField(widget=forms.HiddenInput())
    password = forms.CharField(widget=forms.PasswordInput, max_length=30)
    password2 = forms.CharField(widget=forms.PasswordInput, max_length=30,
                                label='Confirm password')



    class Meta:
        model = CustomUser
        exclude = ['last_login', 'user_permissions', 'groups']
        # labels = {
        #     'password2': 'Confirm password'
        # }
    def clean_email(self):
        email = self.cleaned_data.get('email')

        if email and not re.match(EMAIL_REGEX, email):
            raise forms.ValidationError('Invalid email format')

        return email

    def clean_password2(self):
        confirm_password = self.cleaned_data['password2']
        original_password = self.cleaned_data['password']
        if original_password != confirm_password:
            raise forms.ValidationError("Password doesn't match11")

        return confirm_password

    field_order = ['email', 'password', 'password2']



class ChangePasswordModelForm(PasswordChangeForm):

    # password_old = forms.CharField(widget=forms.PasswordInput, max_length=30,
    #                                label='Provide old password')
    # password = forms.CharField(widget=forms.PasswordInput, max_length=30)
    # password2 = forms.CharField(widget=forms.PasswordInput, max_length=30,
    #                             label='Confirm password')

    old_password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(
            attrs={'autocomplete': 'current-password', 'autofocus': True, 'class': 'form-control',
                   'placeholder': 'Old Password'}),
    )
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'autocomplete': 'new-password', 'class': 'form-control', 'placeholder': 'New Password'}),
        strip=False,
    )
    new_password2 = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(
            attrs={'autocomplete': 'new-password', 'class': 'form-control', 'placeholder': 'Confirm password'}),
    )

    def clean_new_password2(self):
        confirm_password = self.cleaned_data['new_password1']
        original_password = self.cleaned_data['new_password2']
        if original_password != confirm_password:
            raise forms.ValidationError("Password doesn't match11")

        return confirm_password

Sprint 16. Django Forms/om-54-team-21/library/authentication/views.py
# Create your views here.
from django.forms import forms
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.urls import reverse_lazy

from .models import CustomUser
from django.shortcuts import redirect
from django.contrib.auth import logout
from .forms import LoginForm, CustomUserModelFormRegister, \
    ChangePasswordModelForm
from django.contrib.auth.decorators import permission_required


def login_view(request):
    if request.user.is_authenticated:
        return redirect('/')
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return render(request, 'authentication/login_info.html',
                                  {'messageSuccess': 'Authenticate successfully'})
                    # return HttpResponse('Authenticate successfully')
                else:
                    return render(request, 'authentication/login_info.html',
                                  {'message_err': 'Disabled account'})
                    # return HttpResponse('Disabled account')
            else:
                return render(request, 'authentication/login_info.html',
                              {'message_err': 'Invalid login'})
                # return HttpResponse('Invalid login')
        return render(request, 'authentication/login_info.html',
                      {'message_err': 'Invalid login'})
    else:
        form = LoginForm()
        return render(request, 'authentication/login.html', {'form': form})


def register_view(request):
    if request.method == 'POST':
        form = CustomUserModelFormRegister(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if cd['password1'] == cd['password2']:
                user = CustomUser.create(email=cd['email'],
                                         password=cd['password1'],
                                         first_name=cd['first_name'],
                                         role=cd['role'],
                                         middle_name=cd['middle_name'],
                                         last_name=cd['last_name'])
                if not user:
                    return render(request, 'authentication/register.html',
                                  {'form_err': form.error_messages['incorrect_data']})

                return render(request, 'authentication/register_info.html',
                              {'messageSuccess': 'Success'})

            else:
                return render(request, 'authentication/register.html',
                              {'form_err': form.error_messages['password_mismatch'],
                               'form': form,})

        else:
            return render(request, 'authentication/register_info.html',
                          {'form_err': form.errors['email']})
    form = CustomUserModelFormRegister(initial={'email': "email@mail.com"},
                                       auto_id=False, label_suffix=':')
    return render(request, 'authentication/register.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('/')  # or return redirect('/some/url/')

@permission_required('role')
def show_all_users(request):
    # if request.user.is_authenticated and request.user.role == 1:
    data = list(CustomUser.get_all())
    context = {'list_of_user': data}
    return render(request, 'users/users.html', context)


def role_of_user(request):
    if request.user.is_authenticated and request.user.role == 1:
        if request.method == 'POST':
            user_id = request.POST['data']
            if user_id:
                try:
                    data = get_object_or_404(CustomUser, id=user_id)
                    context = {'user': data,
                               'post': True}
                    return render(request, 'users/user_role.html', context)
                except AttributeError:
                    return render(request, 'users/user_role.html',
                                  {'user_by_id': "None user"})

    return render(request, 'users/user_role.html')


def main(request):
    return render(request, 'main/main.html')


@permission_required('role')
def update_user(request, user_id):
    from .forms import UpdateUserModelForm
    user = CustomUser.objects.get(id=user_id)
    form = UpdateUserModelForm(initial={
        'email': user.email,
        'first_name': user.first_name,
        'id': user.id,
        'last_name': user.last_name,
        'middle_name': user.middle_name,
        'role': user.role,
        'is_active': user.is_active,
        'is_staff': user.is_staff,
    })
    if request.method == 'POST':
        form = UpdateUserModelForm(request.POST)
        if form.is_valid():
            user_form = form.save(commit=False)
            user_form.id = user.id
            user_form.save()
        return redirect(reverse_lazy('authentication:users'))
    return render(request, 'users/update_user.html', {'form': form,
                                                     'user':user})


@permission_required('role')
def del_user(request, user_id):
    user = CustomUser.objects.get(id=user_id)
    user.delete()
    return redirect(reverse_lazy('authentication:users'))

from django.contrib.auth.decorators import login_required

@login_required
def change_password(request, user_id=None):
    form = ChangePasswordModelForm(request.user, request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            cd = form.cleaned_data
            user = CustomUser.objects.get(id=user_id)
            # if cd['password2'] != user.password:
            #     return render(request, 'authentication/change_password.html',
            #                   {'form': form,
            #                    'error': 'Old password doesn\'t match'})
            # else:
            user.set_password(cd['new_password1'])
            user.save()
            return render(request, 'authentication/change_password.html',
                          {'form': form, 'resolt': '1'})

    return render(request, 'authentication/change_password.html',
                      {'form': form, })

Sprint 16. Django Forms/om-54-team-21/library/authentication/templates/authentication/change_password.html
{% extends 'base.html' %}
{% block styles %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'author/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'order/css/style.css' %}">
{% endblock %}
{% block title %}Change password{% endblock %}
{% block content %}

  {% if error %}
    <srong><div style="text-align: center; font-size: 1.4rem; color: red">{{ error }}</div></srong>
  {% endif %}
  {% if resolt %}
    <div class="successAdded"> Successful update password {{ resolt }} </div>
  {% endif %}
  <form class="orderAddForm" action="" method="post">

    {% csrf_token %}

    {{ form.as_table }}<br><br>

    <input type="submit" value="Submit">

  </form>

  {#<a>{{resolt}}</a>#}
{% endblock %}

Sprint 16. Django Forms/om-54-team-21/library/authentication/templates/authentication/login.html
{% extends 'base.html' %}
{% block styles %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'login/css/style.css' %}">
{% endblock %}
{% block title %}
Login
{% endblock %}
{% block content %}
  <form class="loginForm" action="" method="post">
    <h3>Login Here</h3>
    {{ form.as_div }}
    {% csrf_token %}
    <button type="submit">Log In</button>
    <br><br>
    <p style="text-align: center">OR</p>
    <div class="social">

      <a class="register" href="{% url 'authentication:register' %}"><div class="register">Register</div></a>

    </div>
  </form>


{% endblock %}

Sprint 16. Django Forms/om-54-team-21/library/authentication/templates/authentication/login_info.html
{% extends 'base.html' %}
{% block styles %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'author/css/style.css' %}">
{% endblock %}
{% block title %}
  Register info
{% endblock %}
{% block content %}

  {% if messageSuccess %}
    <div class="successAdded"> Successful authentication  </div>
    <br>
    <br>
    <p class="linkLogin"><a href="{% url 'authentication:main' %}">Link to main</a></p>
  {% else %}
    <div class="messageErr"> {{ message_err }}  </div>
    <p class="linkRegister"><a style="color: #4e504e" href="{% url 'authentication:login' %}">Try again</a></p>
{#    {% include 'authentication/register.html' %}#}
  {% endif %}



{% endblock %}

Sprint 16. Django Forms/om-54-team-21/library/authentication/templates/authentication/register.html
{% extends 'base.html' %}
{% block styles %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'register/css/style.css' %}">
{% endblock %}
{% block title %}
  Login
{% endblock %}
{% block content %}
  <form class="registerForm" action="" method="post">
    {% csrf_token %}

    {{ form.as_p }}
    {% if form.error_messages %}
      {% for error_message in form.error_messages %}
        <ul>
          <li style="color: red; list-style: none; text-align: center">
            {{ error_message }}
          </li>
        </ul>
      {% endfor %}

    {% endif %}
    <input type="submit" value="Register">
  </form>


{% endblock %}

Sprint 16. Django Forms/om-54-team-21/library/authentication/templates/authentication/register_info.html
{% extends 'base.html' %}
{% block styles %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'register/css/style.css' %}">
{% endblock %}
{% block title %}
  Register info
{% endblock %}
{% block content %}

  {% if messageSuccess %}
    <div class="successAdded"> Successful register  </div>
    <br>
    <br>
    <p class="linkLogin"><a href="{% url 'authentication:login' %}">You can log in now</a></p>
  {% else %}
    <div class="messageErr"> {{ form_err }}  </div>
    <p class="linkRegister"><a href="{% url 'authentication:register' %}">Try again</a></p>
{#    {% include 'authentication/register.html' %}#}
  {% endif %}



{% endblock %}